---
- hosts: elastic_agent_clients
  gather_facts: true
  vars_prompt:
    - name: "elastic_agent_version"
      prompt: "Enter elastic agent version."
      private: no
      default: "{{ elastic_agent_version }}"
    - name: "fleet_url"
      prompt: "Enter fleet url."
      private: no
      default: "{{ fleet_url }}"
    - name: "fleet_token"
      prompt: "Enter fleet token."
      private: yes
  roles:
    - { role: "role/ea-deployer" }
